version: '3'

services:
    postgres_ccat3:
        image: postgres
        ports:
         - "5432:5432"
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: Toor@1234
          POSTGRES_DB: ccat3
        volumes:
         - ./volumes/postgres:/data/postgres